# Generated by Django 5.1.4 on 2024-12-17 19:29

from django.db import migrations

from quiz.enums import UserGroups

def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    
    Group.objects.get_or_create(name=UserGroups.ADMIN_USER.value)
    Group.objects.get_or_create(name=UserGroups.NORMAL_USER.value)

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20241217_1916'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
